services:
  db:
    image: mariadb:10.6
    restart: unless-stopped
    networks: 
      - meetdownnet
    environment:
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=db"
      - "MYSQL_PASSWORD=db"
      - "MYSQL_ROOT_PASSWORD=db"
    volumes:
      - "./docker/db/my.cnf:/etc/mysql/my.cnf:ro"
      - "dbdata:/var/lib/mysql"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: ${BUILD_TARGET}
    restart: unless-stopped
    networks: 
      - meetdownnet
    volumes:
      - "./app/:/app"
      - "./docker/app/php.ini:/usr/local/etc/php/php.ini:ro"
    depends_on:
      - db

  web:
    image: nginx:1.21-alpine
    restart: unless-stopped
    networks: 
      - meetdownnet
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./app/public/:/app"
      - "./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - app

  es:
    image: elasticsearch:7.14.0
    restart: unless-stopped
    networks: 
      - meetdownnet
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  meetdownnet:

volumes:
  dbdata:
  esdata:
