services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: ${BUILD_TARGET}
    restart: unless-stopped
    networks: 
      - meetdownnet
    volumes:
      - "./app/:/app"
    depends_on:
      - db
      - es

  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
      target: dev
    restart: unless-stopped
    networks: 
      - meetdownnet
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "./app/public/:/app"
    depends_on:
      - app

  db:
    image: mariadb:10.6
    build:
      context: .
      dockerfile: docker/db/Dockerfile
      target: dev
    restart: unless-stopped
    networks: 
      - meetdownnet
    environment:
      - "MYSQL_DATABASE=db"
      - "MYSQL_USER=db"
      - "MYSQL_PASSWORD=db"
      - "MYSQL_ROOT_PASSWORD=db"
    volumes:
      - "dbdata:/var/lib/mysql"

  es:
    image: elasticsearch:7.14.0
    restart: unless-stopped
    networks: 
      - meetdownnet
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    volumes:
      - "esdata:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

networks:
  meetdownnet:

volumes:
  dbdata:
  esdata:
